### PR TITLE
Minimal

### PR DESCRIPTION
**Pull request by Fohlen**
Added a working menu and ambient soundtrack for the alpha release.
Further fixes the issues with icon/crosshair

### CODE REVIEW

**Comment by koraa** [comment]
Could you please ask Alexander "pix" Willing to license the GUI under CC >= 3.0 without NC.
The music is also licensed under NC :/

**Comment by Fohlen** [comment]
Will do. The music is a suggestion ofc, we will want to replace it with some custom tracks in the beta?

**Comment by Fohlen** [comment]
I agree that we should first wait until Alexander Willing has explicitely licensed his content under CC-BY-SA (or similliar)

**Comment by koraa** [comment]
Please replace the light background with a dark one. The GUI theme is not adapted for a light background.
A  blurred HD screen shot of one of our maps might do very well in that respect.

**Pull request closed without merging**
